site_name: ASTRA-RL Toolbox Documentation
site_author: Duncan Eddy
site_description: Adaptive Stress Testing for Robust AI & Reinforcement Learning â€” a toolbox for testing and improving the robustness of AI systems.
site_url: https://github.com/sisl/astra-rl
repo_url: https://github.com/sisl/astra-rl
docs_dir: docs
use_directory_urls: false

plugins:
  - search
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: iso_date

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
    - stylesheets/extra.css

theme:
  name: material
  # logo: assets/icon.png
  # favicon: assets/favicon.png
  highlightjs: true
  hljs_languages:
      - yaml
      - python
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: black
      toggle:
          icon: material/weather-night
          name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: black
      toggle:
          icon: material/weather-sunny
          name: Switch to light mode
  features:
      - navigation.instant
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.expand
      - toc.follow

nav:
  - ASTRA: index.md
  - Getting Started: getting_started.md
  - Tutorials: 
      - tutorials/index.md
      - tutorials/training_an_evaluator.md
      - tutorials/running_an_evaluation.md
  - API Reference: 
      - api/index.md
      - Core Module:
          - api/core/index.md
          - api/core/common.md
          - api/core/problem.md
          - api/core/environment.md
          - api/core/moderator.md
          - api/core/algorithm.md
      - Algorithms:
          - api/algorithms/index.md
          - api/algorithms/dpo.md
      - Moderators:
          - api/moderators/index.md
          - api/moderators/detoxify.md
      - Training:
          - api/training/index.md
          - api/training/harness.md
          - api/training/trainer.md
      - Methods:
          - api/methods/index.md
          - api/methods/ast_problem.md
  - Contributing: contributing.md
      