name: Publish Release

# Only trigger on tags
on:
  release:
    types: [published]

jobs:
  unit-tests:
    uses: ./.github/workflows/run_unit_tests.yml

  build_wheel:
    name: Build wheel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only need to build for one python version
        # because the wheel is compatible with all 3.12+ versions currently
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --frozen

      - name: Build wheel
        run: uv build --wheel

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.python-version }}
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only need to build for one python version
        # because the wheel is compatible with all 3.12+ versions currently
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --frozen

      - name: Build wheel
        run: uv build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist-${{ matrix.python-version }}
          path: dist/*.tar.gz

  update-docs:
    uses: ./.github/workflows/update_docs.yml
    needs: [ unit-tests, build_wheel, build_sdist ]

  upload_pypi:
    needs: [ build_sdist, build_wheel ]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: dist
          merge-multiple: true

      - name: List files in dist
        run: ls -lR dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        # Uncomment below for testing
        # with:
        #   repository-url: https://test.pypi.org/legacy/
